version: 2.1

orbs:
  central-orb: https://raw.githubusercontent.com/nanophate-cci/central-template-orb/refs/heads/main/central-orb.yml

jobs:
  build:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "This comes from orginal repo~!"

  test:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run: echo "this is test job"

workflows:
  main:
    jobs:
      - build
      - test:
          override-with: central-orb/custom-test
